logins_ip:
  limit: 5
  period: 30
  path: /users/sign_in

post_creation:
  limit: 3
  period: 600
  path: /posts

comment_creation:
  limit: 5
  period: 45
  path: /comments

comment_reply_creation:
  limit: 5
  period: 45
  path: /comment_replies

messages_creation:
  limit: 20
  period: 10
  path: /messages

group_invitation_creation:
  limit: 5
  period: 60
  path: /group_invitations

default:
  limit: 10
  period: 10
  method: POST
